{
  parserClass="org.kathrynhuxtable.gdesc.gdescplugin.parser.GDescParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="GDesc"
  psiImplClassSuffix="Impl"
  psiPackage="org.kathrynhuxtable.gdesc.gdescplugin.psi"
  psiImplPackage="org.kathrynhuxtable.gdesc.gdescplugin.psi.impl"

  elementTypeHolderClass="org.kathrynhuxtable.gdesc.gdescplugin.psi.GDescTypes"
  elementTypeClass="org.kathrynhuxtable.gdesc.gdescplugin.psi.GDescElementType"
  tokenTypeClass="org.kathrynhuxtable.gdesc.gdescplugin.psi.GDescTokenType"

  psiImplUtilClass="org.kathrynhuxtable.gdesc.gdescplugin.psi.impl.GDescPsiImplUtil"
}

gdescFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY
{
  mixin="org.kathrynhuxtable.gdesc.gdescplugin.psi.impl.GDescNamedElementImpl"
  implements="org.kathrynhuxtable.gdesc.gdescplugin.psi.GDescNamedElement"
  methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}
